### ISSUE TITLE
Stars dont match the ratings in listscreen

### ISSUE THREAD

**Issue by jose-vs** [jose-vs/Loocate#16]
![image](https://user-images.githubusercontent.com/67150374/116237426-4f38b380-a7b4-11eb-9174-74b619926905.png)

**Comment by David10088** [comment]
![issue1](https://user-images.githubusercontent.com/68878934/116339889-5acabf80-a832-11eb-8e9f-46fc0a69f998.PNG)
It's because the stars are showing how many reviews, instead of ratings.  Fixed 
![image](https://user-images.githubusercontent.com/68878934/116339975-7df56f00-a832-11eb-8144-0961f4ead484.png)
